apiVersion: v1
kind: Service
metadata:
  name: docker-registry-http
  labels:
    app: docker-registry
spec:
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 31500
  type: NodePort
  selector:
    app: docker-registry
