#!groovy
node('jenkins-slave') {
   // Mark the code checkout 'stage'....
   stage 'Checkout'

   // Get some code from a GitHub repository
   git url: 'https://github.com/VineetReynolds/NoveaBank.git', branch: 'step-3'

   // Get the Maven 3 tool.
   // ** NOTE: This 'Maven3' maven tool must be configured
   // **       in the global configuration.           
   def mvnHome = tool 'Maven3'
   env.PATH = "${mvnHome}/bin:${env.PATH}"
   
   // Mark the code build 'stage'....
   stage 'Build'
   dir('backend') {
    sh "mvn clean package"
   }

   stage 'Create Docker Image'
   // Run the docker build for the Dockerfile in the frontend directory
   dir('backend') {
       sh "sudo docker build --no-cache=true -t 192.168.99.100:31500/vineetreynolds/noveabank-backend:1.0-${env.BUILD_NUMBER} --pull=true ."
       sh "sudo docker push 192.168.99.100:31500/vineetreynolds/noveabank-backend:1.0-${env.BUILD_NUMBER}"
   }
}
