apiVersion: v1
kind: Service
metadata:
  name: jenkins-http
  labels:
    app: jenkins
spec:
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31080
  type: NodePort
  selector:
    app: jenkins