apiVersion: v1
kind: Service
metadata:
  name: keycloak-http
  labels:
    app: noveabank-keycloak
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30880
  type: NodePort
  selector:
    app: noveabank-keycloak